apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yml convert
    kompose.version: 1.26.1 (HEAD)
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9102'
    prometheus.io/path: '/metrics'
  creationTimestamp: null
  labels:
    io.kompose.service: promstats
  name: promstats
spec:
  ports:
    - name: "udp"
      port: 9125
      protocol: UDP
      targetPort: 9125
    - name: "tcp"
      port: 9102
      protocol: TCP
      targetPort: 9102
  selector:
    io.kompose.service: promstats
status:
  loadBalancer: {}
